name: isox
description: Run your Isolates with bidirectional communication. Isox provides a simple request/reply pattern to communicate with your Isolates.
version: 0.2.0-nullsafety.0
homepage: https://github.com/AurityLab/isox
issue_tracker: https://github.com/AurityLab/isox/issues

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.12
